name: Github Pages

on:
  push:
    branches: [master]

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['14']
    name: Node ${{ matrix.node }}
    env:
      CI: true
      # temporary disable preflight check until CRA loosen babel-loader version dependency that clashes with storybook babel-loader version
      # https://github.com/storybookjs/storybook/issues/5183
      SKIP_PREFLIGHT_CHECK: true
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm ci

      - name: Build docs
        run: npm run build:docs

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: storybook-static
