name: Release

on:
  push:
    branches: [master, beta]

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['14', '16']
    name: Node ${{ matrix.node }}
    env:
      CI: true
      # temporary disable preflight check until CRA loosen babel-loader version dependency that clashes with storybook babel-loader version
      # https://github.com/storybookjs/storybook/issues/5183
      SKIP_PREFLIGHT_CHECK: true
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm ci

      - name: Execute coverage report
        run: npm test -- --coverage

      - name: Build library
        run: npm run build:lib

      - name: Configure registry
        run: npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish library
        run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish coverage
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
